config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  root 'home_page#home'
  post '/contact', to: 'home_page#contact'
  
  scope "/admin" do
  	get '/dashboard', to: 'editors#dashboard'
  	get '/register', to: 'editors#new'
  	post '/register', to: 'editors#create'
  	get '/login', to: 'sessions#new'
  	post '/login', to: 'sessions#create'
  	delete '/logout', to: 'sessions#destroy'
  	resources :editors
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
	validates :name, presence: true
	validates :email, presence: true
	validates :message, presence: true
end

app/models/editor.rb
class Editor < ApplicationRecord
	before_save { email.downcase! }
	validates :name, presence: true, length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum: 255 },
										format: { with: VALID_EMAIL_REGEX },
										uniqueness: { case_sensitive: false }
	has_secure_password
	validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

	def Editor.digest(string)
		cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(unencrypted_password, cost: cost)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/editors_controller.rb
class EditorsController < ApplicationController

	def dashboard
  end

  def index
	end
  
  def show
  	@editor = Editor.find(params[:id])
  end

  def new
  	@editor = Editor.new
  end

  def create
  	@editor = Editor.new(editor_params)
  	if @editor.save
  		flash[:success] = "#{@editor.name} created."
  		redirect_to editors_url
  	else
  		render 'new'
  	end
  end

  private

  	def editor_params
  		params.require(:editor).permit(:name, :email, :password, :password_confirmation)
  	end
end

app/controllers/home_page_controller.rb
class HomePageController < ApplicationController
  def home
    @contact = Contact.new
  end

  def contact
    create_contact = Contact.create(contact_params)
    if create_contact.valid?
      ContactMailer.contact_me(create_contact).deliver_now
      respond_to do |format|
        format.html { redirect_to root_url }
        format.js
      end
    end
  end

  private
    def contact_params
      params.require(:contact).permit(:name, :email, :message)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	editor = Editor.find_by(email: params[:session][:email].downcase)
  	if editor && editor.authenticate(params[:session][:password])
  		log_in editor
  		redirect_to dashboard_url
  	else
  		flash.now[:danger] = 'Invalid email or password combination'
  		render 'new'
  	end
  end

  def destroy
    log_out
    redirect_to login_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def page_title(prefix_title = '')
    base_title = "I'm Deri"
    if prefix_title.empty?
      base_title
    else
      prefix_title +  " | " + base_title
    end
  end

  def render_header(admin_page = '')
  	if admin_page.eql? "admin"
  		render "shared/header_admin"
  	else
  		render "shared/header"
  	end
  end
end

app/helpers/editors_helper.rb
module EditorsHelper
end

app/helpers/home_page_helper.rb
module HomePageHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def log_in(editor)
		session[:user_id] = editor.id
	end

	def current_editor
		@current_editor ||= Editor.find_by(id: session[:user_id])
	end

	def logged_in?
		!current_editor.nil?
	end

	def log_out
		session.delete(:user_id)
		@current_editor = nil
	end
	
end

app/views/application/_header.html.erb
<!-- Navigation -->
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header page-scroll">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#page-top"><%= image_tag("logo.png") %></a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li class="hidden">
                    <a href="#page-top"></a>
                </li>
                <li class="page-scroll">
                    <a href="#portfolio">Workshop</a>
                </li>
                <li class="page-scroll">
                    <a href="#about">About</a>
                </li>
                <li class="page-scroll">
                    <%= link_to("Blogs", "#") %>
                </li>
                <li class="page-scroll">
                    <a href="#contact">
                        <i class="fa fa-envelope-o fa-lg"></i>
                    </a>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>

app/views/editors/dashboard.html.erb
<% provide(:title, "Dashboard") %>
<% provide(:admin_page, "admin") %>
<section class="admin">
<div class="container">
<div class="row">
	<div class="col-lg-12 text-center">
        <h2>Command Center</h2>
        <div class="horizontal-line"></div>
    </div>
</div>
</div>
</section>

app/views/editors/index.html.erb
<% provide(:title, "All editors") %>
<section class="admin">
<div class="container">
<div class="row">
	<div class="col-lg-12 text-center">
        <h2>All Editors</h2>
        <div class="horizontal-line"></div>
    </div>
</div>
</div>
</section>

app/views/editors/new.html.erb
<% provide(:title, 'Create new editor') %>
<% provide(:admin_page, "admin") %>
<section class="admin">
<div class="container">
<div class="row">
    <div class="col-lg-12 text-center">
        <h2>Create Editor</h2>
        <div class="horizontal-line"></div>
    </div>
</div>
<div class="row">
	<div class="col-md-6 col-md-offset-3">
    <%= form_for @editor, url: register_path do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
        <div class="row control-group">
            <div class="form-group col-xs-12 floating-label-form-group controls">
              <%= f.label :name %>
              <%= f.text_field(:name, class: 'form-control', placeholder: "Name*") %>
            </div>
        </div>
        <div class="row control-group">
            <div class="form-group col-xs-12 floating-label-form-group controls">
              <%= f.label :email %>
              <%= f.email_field(:email, class: "form-control", placeholder: "Email Address*") %>
            </div>
        </div>
        <div class="row control-group">
            <div class="form-group col-xs-12 floating-label-form-group controls">
              <%= f.label :password %>
              <%= f.password_field(:password, class: "form-control", placeholder: "Password*") %>
            </div>
        </div>
        <div class="row control-group">
            <div class="form-group col-xs-12 floating-label-form-group controls">
              <%= f.label :password_confirmation %>
              <%= f.password_field(:password_confirmation, class: "form-control", placeholder: "Password Confirmation*") %>
            </div>
        </div>
        <br>
        <div class="row">
            <div class="form-group col-xs-12">
              <%= f.submit 'Create Editor', class: "btn btn-success btn-lg" %>
            </div>
        </div>
    <% end %>
  </div>
</div>
</div>
</section>

app/views/editors/show.html.erb
<% provide(:title, @editor.name) %>
<% provide(:admin_page, "admin") %>
<section class="admin">
<div class="container">
<div class="row">
	<aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= @editor.name %>
      </h1>
    </section>
  </aside>
</div>
</div>
</section>

app/views/home_page/_contact_me.html.erb
<div class="container">
    <div class="row">
        <div class="col-lg-12 text-center">
            <h2>Contact Me</h2>
            <div class="horizontal-line"></div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-8 col-lg-offset-2">
        <div id="result"></div>
        <%= form_for @contact, url: contact_path, html: { id: "contactForm", novalidate: "novalidate" }, remote: true do |f| %>
            <div class="row control-group">
                <div class="form-group col-xs-12 floating-label-form-group controls">
                    <%= f.label :name %>
                    <%= f.text_field(:name, class: 'form-control', placeholder: "Name*", data: {:validation => "required", "validation-error-msg" => "Name cannot be empty"}) %>
                </div>
            </div>
            <div class="row control-group">
                <div class="form-group col-xs-12 floating-label-form-group controls">
                    <%= f.label :email %>
                    <%= f.email_field(:email, class: "form-control", placeholder: "Email Address*", data: {:validation => "required email", "validation-error-msg" => "A valid email address is required"}) %>
                </div>
            </div>
            <div class="row control-group">
                <div class="form-group col-xs-12 floating-label-form-group controls">
                    <%= f.label :message %>
                    <%= f.text_area(:message, class: "form-control", placeholder: "Message*", rows: 5, data: {:validation => "required", "validation-error-msg" => "Message cannot be empty"}) %>
                </div>
            </div>
            <br>
            <div class="row">
                <div class="form-group col-xs-12">
                    <%= f.button 'Send', class: "btn btn-success btn-lg", data: { disable_with: "<i class='fa fa-spinner fa-spin'></i> Sending..."} %>
                </div>
            </div>
        <% end %>
        </div>
    </div>
</div>

app/views/home_page/_contact_response.html.erb
<div class="alert alert-success" role="alert">Thank you for your message!</div>

app/views/home_page/contact.js.erb
$("#result").html("<%= escape_javascript(render('contact_response')) %>");
$("#contactForm").trigger("reset");

app/views/home_page/home.html.erb
<!-- Header -->
<header>
<div class="bg-overlay pattern"></div>
        <div class="row">
            <div class="col-lg-12">
                <%= image_tag("profile.png") %>
                <div class="intro-text">
                    <span class="name">Hello, I'm Deri</span>
                    <div class="horizontal-line"></div>
                    <span class="skills">Just started learning to code in iOS - Ruby on Rails</span>
                </div>
            </div>
        </div>
    </div>
</header>

<!-- Portfolio Grid Section -->
<section id="portfolio">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h2>Workshop</h2>
                <div class="horizontal-line"></div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-2">
            </div>
            <div class="col-sm-2">
            </div>
            <div class="col-sm-2 portfolio-item">
                <a href="#portfolioModal1" class="portfolio-link" data-toggle="modal">
                    <div class="caption">
                        <div class="caption-content">
                            <i class="fa fa-search-plus fa-3x"></i>
                        </div>
                    </div>
                    <%= image_tag("portfolio/mpl.png", class: "img-responsive") %>
                </a>
            </div>
            <div class="col-sm-2 portfolio-item">
                <a href="#portfolioModal2" class="portfolio-link" data-toggle="modal">
                    <div class="caption">
                        <div class="caption-content">
                            <i class="fa fa-search-plus fa-3x"></i>
                        </div>
                    </div>
                    <%= image_tag("portfolio/mdtaufan.jpg", class: "img-responsive") %>
                </a>
            </div>
            <div class="col-sm-2">
            </div>
            <div class="col-sm-2">
            </div>
        </div>
    </div>
</section>

<!-- About Section -->
<section class="success" id="about">
<div class="bg-overlay pattern"></div>
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h2>About</h2>
                <div class="horizontal-line"></div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-6 col-lg-offset-3">
                <p>This website is dedicated to my journey of learning to code for iOS and Ruby on Rails.</p>
            </div>
        </div>
    </div>
</section>

<section id="contact">
    <%= render 'contact_me' %>
</section>

<!-- Footer -->
<footer class="text-center">
    <div class="footer-above">
        <div class="container">
            <div class="row">
                <div class="footer-col col-md-6">
                    <h3>Location</h3>
                    <p>Nijmegen, The Netherlands <br>Banda Aceh, Indonesia</p>
                </div>
                <div class="footer-col col-md-6">
                    <h3>Around the Web</h3>
                    <ul class="list-inline">
                        <li>
                            <a href="https://twitter.com/deritaufan" class="btn-social btn-outline"><i class="fa fa-fw fa-twitter"></i></a>
                        </li>
                        <li>
                            <a href="http://id.linkedin.com/in/deritaufan" class="btn-social btn-outline"><i class="fa fa-fw fa-linkedin"></i></a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="footer-below">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    Copyright &copy; MDTaufan.com <%= Time.now.strftime("%Y") %>
                </div>
            </div>
        </div>
    </div>
</footer>


<!-- Scroll to Top Button (Only visible on small and extra-small screen sizes) -->
<div class="scroll-top page-scroll visible-xs visible-sm">
    <a class="btn btn-primary" href="#page-top">
        <i class="fa fa-chevron-up"></i>
    </a>
</div>

<!-- Portfolio Modals -->
<div class="portfolio-modal modal fade" id="portfolioModal1" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-content">
        <div class="close-modal" data-dismiss="modal">
            <div class="lr">
                <div class="rl">
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2">
                    <div class="modal-body">
                        <h2>Mobile Phone Locator</h2>
                        <div class="horizontal-line"></div>
                        <%= image_tag("portfolio/mpl.png", class: "img-responsive img-centered") %>
                        <p>Be ready to amaze your friends with this great app. Simply enter the phone number of your friends who sit next to you and the app will start 'locating' their phones.</p>
                        <ul class="list-inline item-details">
                            <li>Platform:
                                <strong>iOS
                                </strong>
                            </li>
                            <li>Code Used:
                                <strong>Swift
                                </strong>
                            </li>
                        </ul>
                        <%= link_to("https://itunes.apple.com/id/app/mobile-phone-locator/id1071726132?mt=8") do %>
                            <%= image_tag("download_appstore.png", class: "img-responsive img-centered") %>
                        <% end %>
                        <button type="button" class="btn btn-default" data-dismiss="modal"><i class="fa fa-times"></i> Close</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="portfolio-modal modal fade" id="portfolioModal2" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-content">
        <div class="close-modal" data-dismiss="modal">
            <div class="lr">
                <div class="rl">
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2">
                    <div class="modal-body">
                        <h2>MDTaufan.com</h2>
                        <div class="horizontal-line"></div>
                        <%= image_tag("portfolio/mdtaufan-modal.jpg", class: "img-responsive img-centered") %>
                        <p>MDTaufan.com is my personal website to showcase my journey on learning to code.</p>
                        <ul class="list-inline item-details">
                            <li>Platform:
                                <strong>Web App
                                </strong>
                            </li>
                            <li>Code Used:
                                <strong>Ruby on Rails
                                </strong>
                            </li>
                        </ul>
                        <button type="button" class="btn btn-default" data-dismiss="modal"><i class="fa fa-times"></i> Close</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= page_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic' %>
    <%= stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Raleway:400,700,600,500,300,200,100,800,900' %>
    <%= stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
  </head>
  <body id="page-top" class="index">
  	<%= render_header(yield(:admin_page)) %>
    <%= render "shared/flash_message" %>
    <%= yield %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      Oops, you got <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_message.html.erb
<div class="container">
<% flash.each do |message_type, message| %>
	<div class="alert alert-<%= message_type %> text-center"><%= message %></div>
<% end %>
</div>

app/views/shared/_header.html.erb
<!-- Navigation -->
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header page-scroll">
            <button type="button" class="navbar-toggle" data-toggle="collapse"
             data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <%= link_to("#page-top", class: "navbar-brand") do %>
                <%= image_tag("logo.png") %>
            <% end %>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li class="hidden">
                    <a href="#page-top"></a>
                </li>
                <li class="page-scroll">
                    <a href="#portfolio">Workshop</a>
                </li>
                <li class="page-scroll">
                    <a href="#about">About</a>
                </li>
                <li class="page-scroll">
                    <%= link_to("Blogs", "#") %>
                </li>
                <li class="page-scroll">
                    <a href="#contact">
                        <i class="fa fa-envelope-o fa-lg"></i>
                    </a>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>

app/views/shared/_header_admin.html.erb
<!-- Navigation -->
    <nav class="navbar navbar-default nav-admin">
      <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header page-scroll">
          <button type="button" class="navbar-toggle" data-toggle="collapse"
           data-target="#bs-example-navbar-collapse-1">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
          </button>
          <%= link_to(root_path, class: "navbar-brand") do %>
              <%= image_tag("logo.png") %>
          <% end %>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <li class="hidden">
                <a href="#page-top"></a>
            </li>
            <% if logged_in? %>
              <li class="page-scroll">
                <%= link_to(dashboard_path, class: "navbar-brand") do %>
                  <i class="fa fa-tachometer fa-lg"></i>
                <% end %>
              </li>
              <li class="page-scroll">
                <%= button_to "Logout", logout_path, method: :delete, class: "btn btn-success navbar-btn" %>
              </li>
            <% end %>
          </ul>
        </div>
        <!-- /.navbar-collapse -->
      </div>
      <!-- /.container-fluid -->
    </nav>